defaults:
  - _self_
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "simclr-imagnet-linear"
pretrained_feature_extractor: "/projects/imagenet_synthetic/model_checkpoints/solo-learn/solo_trained_models/simclr/shs7ffg0/100-paper-simclr-synth-imagenet-seed-200-shs7ffg0-ep=99.ckpt"
backbone:
  name: "resnet50"
pretrain_method: "simclr"
data:
  dataset: "imagnet"
  train_path: "/datasets/imagenet/train"
  val_path: "/datasets/imagenet/val"
  format: "dali"
  num_workers: 4
optimizer:
  name: "lars"
  batch_size: 512
  lr: 0.1
  weight_decay: 0
scheduler:
  name: "warmup_cosine"
  warmup_epochs: 0
  scheduler_interval: "epoch"
checkpoint:
  enabled: True
  dir: "/projects/imagenet_synthetic/model_checkpoints/solo-learn/solo_trained_models"
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 100
devices: 4
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16
