defaults:
  - _self_
  - augmentations: synthetic_symmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "simclr-imagenet-diff-25"
method: "simclr"
backbone:
  name: "resnet50"
method_kwargs:
  proj_hidden_dim: 4096
  proj_output_dim: 512
  temperature: 0.2
data:
  dataset: imagenet
  train_path: TRAIN_PATH
  val_path: VAL_PATH
  synthetic_path: DIFFUSION_SYNTHETIC_PATH
  synthetic_index_min: 0
  synthetic_index_max: 9
  generative_augmentation_prob: 0.25
  format: "dali"
  num_workers: 4
optimizer:
  name: "lars"
  batch_size: 256
  lr: 0.3
  classifier_lr: 0.1
  weight_decay: 1e-6
  kwargs:
    clip_lr: True
    eta: 0.02
    exclude_bias_n_norm: True
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: SAVE_PATH
  frequency: 1
auto_resume:
  enabled: True

# overwrite PL stuff
max_epochs: 100
devices: 4
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16-mixed
