defaults:
  - _self_
  - augmentations: asymmetric.yaml
  - wandb: private.yaml
  - override hydra/hydra_logging: disabled
  - override hydra/job_logging: disabled

# disable hydra outputs
hydra:
  output_subdir: null
  run:
    dir: .

name: "paper-simsiam-synth-imagenet"
method: "simsiam"
backbone:
  name: "resnet50"
method_kwargs:
  proj_hidden_dim: 2048
  proj_output_dim: 2048
  pred_hidden_dim: 512
data:
  dataset: imagenet
  train_path: "/datasets/imagenet/train"
  val_path: "/datasets/imagenet/val"
  synthetic_path: "/projects/imagenet_synthetic/arashaf_stablediff_batched"
  synthetic_index_min: 0
  synthetic_index_max: 9
  generative_augmentation_prob: 1
  format: "dali"
  num_workers: 4
optimizer:
  name: "sgd"
  batch_size: 128
  lr: 0.05
  classifier_lr: 0.1
  weight_decay: 1e-4
scheduler:
  name: "warmup_cosine"
checkpoint:
  enabled: True
  dir: "/projects/imagenet_synthetic/model_checkpoints/solo-learn/solo_trained_models"
  frequency: 1
auto_resume:
  enabled: False

# overwrite PL stuff
max_epochs: 100
devices: 4
sync_batchnorm: True
accelerator: "gpu"
strategy: "ddp"
precision: 16-mixed
